# Generated by Django 3.1.4 on 2021-01-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0002_auto_20210109_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
